### PR TITLE
Add Feature Request and Bug Report issue templates

### PR DESCRIPTION
**Pull request by MitchellTFord**
This simplifies the process of submitting Feature Requests and Bug Reports

### CODE REVIEW

**Review by nickvichai — CHANGES_REQUESTED** [review]
Looks like you were supposed to add a template for Feature Request as well, did you leave it out on purpose?

**Comment by MitchellTFord** [comment]
> Looks like you were supposed to add a template for Feature Request as well, did you leave it out on purpose?

I was kinda confused when I got this notification since this is a draft PR (or so I thought). Thankfully, GitHub keeps a changelog for things like this. 

image

It was @wament !!! 

I'll add the missing template now @nickvichai

**Comment by MitchellTFord** [comment]
@nickvichai I update it

**Review by nickvichai — APPROVED** [review]
Admiral Commits 👍

**Pull request merged**
